### PR TITLE
Some refactors

### PR DESCRIPTION
**Pull request by Wunkolo**
I edited and changed a lot of code(untested) regarding the general structure of this. This project seems to be using codeblocks while I use visual studio so I had to just edit the files manually.
Before diving into the opcode case switch some design-wise changes can be made. That grind-work can be deferred to later once everything is in place such as rom reading and having concise code.

Unions can be used to make the handling of registers easier.
Unions let you pick at the same region of memory in different ways so a 16 bit register can be accessed by its individual bytes.

```
    typedef union
    {
        struct
        {
            uint8_t Low;
            uint8_t High;
        };
        uint16_t Word;
    } Register16;
```

This "register16" object would be 16 bits(2 bytes) total and can be accessed using `.word` or `.Low`/`.High` to access the individual bytes.
The `define` chunks can be replaced with enums with can contain your constant variables. Ex:

```
//FLAG bits
enum Flags
{
    ZERO = 0x80,    // Zero Flag
    SUB = 0x40, // Add/Subtract
    HALF_CARRY = 0x20,  // Half-Carry
    CARRY = 0x10    // Carry
};
```

Functions that don't actually modify their class's variables can be marked with `const`.

```
void        memWrite(uint16_t addr, uint8_t value);
uint8_t     memRead(uint16_t addr);
```

can be made into

```
void        memWrite(uint16_t addr, uint8_t value);
uint8_t     memRead(uint16_t addr) const;
```

Also rather than making local copies of variables and then modifying them you can just access the variables directly since these variables are a part of their class.
Bitfields can be used to restrict certain types to individual bits.
A bool can be represented using an int or a short or a char

```
struct Flags
{
    bool zero : 1;
    bool sub : 1;
    bool hc : 1;
    bool carry : 1;
    char Pad : 4;//Fills up the last 4 unused bits
}
```

The total size for "Flags" struct would be 1 byte. Each of those bool elements would take up those individual bytes. If I wanted to I could write an "AF" register using a union and have this struct used as the Upper bytes to make handling flags easier.
A lot of these getters and setter functions are only used internally and could be in-lined to the array accesses they are doing.
memWrite and memRead would need functions though due to the additional logic that needs to be carried out when writing and reading to registers or memory banks.
If it needs additional logic, it merits the use of a function. If the function is just containing an array accessor then just use the array accessor.
Same goes to the "increment stack pointer" functions and such.

### CODE REVIEW

**Comment by Quaker762** [comment]
Okay I get everything except the flags. I was using those defines as bitmasks, as shown here (http://marc.rawer.de/Gameboy/Docs/GBCPUman.pdf, page 62), flags is also a register, so would storing the direct values in the enum make sense?

**Comment by Wunkolo** [comment]
The enum exists so you can quickly test or set the register against flags to see if it is set.
Ex: if you wanted to see if the ZERO flag is set you can do
`if(AF.High & ZERO)` right in the middle of your code so it's comparing two integers rather than having an additional layer of logic to extract the flags into bool values.
The enum just stores an array of constants that are used at compile-time and turned into their corresponding integer values. Kind of works the same way as the `#define` you had before.

**Comment by Quaker762** [comment]
Ah okay. Also, in the example you used, would F be the low or high byte (as the GB is little endian). I can't actually find any information regarding this.

EDIT: Nevermind, I see High is the second value in the struct, making the lower byte

**Comment by Wunkolo** [comment]
I believe it is little endian. The only time you have to worry about endian is when you have 16 bit integers since endian would decide which order the bytes are in. Big endian is more of an anomaly these days.

**Comment by Quaker762** [comment]
Okay thank you.

**Pull request merged**
