### PR TITLE
MBC/ROM Header improvements.

### PR DESCRIPTION
**Pull request by darrena092**
Not really much to say. I saw your project and I'm interested in helping.

I've created a new header containing all of the definitions for each MBC type, ROM size and RAM size. Aside from that, I've moved the ROM header variable definitions into a struct to keep things more tidy. I've also modified Cartridge::getROMHeaderInfo() to load the relevant data about the ROM.

Hope this helps! Let me know if I can do anything else.

### CODE REVIEW

**Comment by darrena092** [comment]
I've also gone and modified Cartridge::rom0 to be dynamically allocated depending on the size of the rom, so you can get bigger things than Tetris into memory haha.

**Comment by Quaker762** [comment]
Sorry for the late merge, I haven't checked the project in a while and didn't think anyone would submit a PR haha. Anyway, thanks for the changes and feel free to add code whenever you want. I'm thinking of making this a full debugging suite for GameBoy programming, so if you have anything else to contribute, please by all means do (I'm still a bit new to emulation programming)

**Comment by Quaker762** [comment]
Also I just noticed you've also got a GameBoy project going as well. Would you like to merge the two and start a larger project, seeing as we've both got different portions of the GameBoy implemented?

**Comment by darrena092** [comment]
Not a problem. I've been pretty busy lately too, so I haven't been on here to check the PR. I'm fairly new to it as well. I was doing my GameBoy project as a learning experience more than anything else. 
I'd be more than happy to merge the two. It's been a long time since anyone has made a really good GameBoy emulator. 

My goal would be similar to yours. I'd like to make an emulator that can be used for just relaxing and gaming, but also something that could be a useful development tool. In time I'd also like to implement GBC and GBA support too. What do you think?

If you like the sound of it, let me know and we can work out how to merge the two code bases to keep the best parts of both projects.

**Comment by Quaker762** [comment]
Definitely. It would be good to have a complete debugging suite for each gameboy model (even maybe the super Gameboy, pocket etc, if there's much of a difference) as well as an emulator that can be used or casual gaming. You're right as well, besides Visual Boy Advance I can't think of any other good, serious Gameboy emulators around.

I'm not sure what parts we should keep from both. I've got an alright CPU started, and the registers are about more efficient to access than the ones you have (using unions) which just makes it a bit cleaner and easier to access registers.

Apart from that, lets get merging!

**Comment by darrena092** [comment]
Well that's great, we seem to have the same goal in mind.

Okay, so here's what I'm thinking for the merge.
- CPU:
  We should keep the register unions from your CPU. It's definitely a cleaner way of doing things. But we could possibly put the registers into a struct also. For example, accessing the PC could be something like `Registers.PC.Word`. I feel that we should keep the opcode array (pointer to member functions) from my CPU. I just think that it's a cleaner way of doing things, and it's easier to find specific opcodes for debugging etc.
- MMU:
  I think that we should keep my MMU. It has some basic memory mapping, and also the foundations for bank switching, however it is still far from completion.
- Cartridge:
  We should definitely use the code from your project for this, as I haven't made much of a start of this in mine. I haven't really even looked at it. All that my project is capable of is loading a basic ROM like Tetris. It would be pretty trivial even from where your project is to implement loading multiple banks.

Aside from all of this, I have the start of a graphics core implemented. It follows a finite state machine model, but doesn't do an awful lot at the minute. Have a look at it and tell me if you want to run with that for our graphics implementation.

One other consideration is that we'll have to be cross compatible right from the start. I develop on Linux, and I can see from your code::blocks project that you're on Windows. This should be quite simple if we stick to using SDL2, as the event code etc will be exactly the same for both Linux and Windows. I think that the only issue we could have is threading. In my code, I use a thread for the emulator, and another for the debugger. The issue is that Windows isn't POSIX compatible, but I could just wrap Linux specific code in something like `#ifdef _Linux` and you could do something similar for Windows code. Should be easy enough as long as we keep everything thread safe.

Sound good? Let me know if you have anything else to add, or if this is okay to do and I'll get to work :)

**Comment by Quaker762** [comment]
Sounds good, Your MMU is definitely better and we should port that across seeing as you have some clear idea on how bank switching works... Having a struct for the registers sounds good for keeping everything a little bit cleaner, but I'm not sure if it's exactly necessary (seems like we're just wrapping it up a bit more, but it does logically make sense to have everything in a Register struct)

Keeping your opcode lookup table sounds good as well, I only had the switch-case because that's what I'm used to haha. It does make everything a hell of a lot neater. Yes, definitely bring your Graphics code across, I was putting off doing it as I had no idea where to start. 

As for platform dev, using `#ifdef` sounds good (I guess we'd just use it where threads are defined??), I'm a little rusty with Windows development (I've mainly programmed Java on Windows and a bit of C++ on Linux) so I'll have to read up on some thread stuff. 

Also, another thing we should think of, how do we return how many cycles each instruction uses? At the moment, my cycle function returns how many cycles the instruction takes, but I'm not sure how to actually limit these cycles, if we need to at all. 

Seeing as we'll probably use most of your classes, should we use your project on Github, or would you want to bring your code across to this one?

**Comment by darrena092** [comment]
Awesome. I think I'd rather wrap them up in a struct just to keep things organised (I can be a bit of a neat freak with coding lol).

So we'll keep the opcode table then. I've done some research into it, and apparently it'll be roughly as efficient as the switch case anyways.

I'm really not too versed in windows development at all. I have an idea of how it works, but advanced stuff like threading, no idea. We could even look at using some sort of POSIX thread library for windows. We'll also need to use a compiler on windows that's compatible with C++11 for the opcode table. I'd imagine a recent build of MinGW should do the job.

At the minute, I have the machine and clock cycles taken being saved to a member variable and then added to another variable that keeps track of total machine and clock cycles taken so far. The cycles are also passed to the GPU, as the GPU and CPU must be kept in sync. They're then used to define which state the GPU is in at any given time.

Not really sure about timing at the minute. It'll probably be a case of using the SDL pause function if we're running to fast to keep things at the right speed. Maybe at the end of each cycle. I'd really like to keep the speed very accurate. But we should cross that bridge when we come to it haha.

I think that we should maybe create a new repository. I'd be happy enough to do it on my GitHub, then it'd just be a case of doing an initial commit of the merged code and we'd both have write access. Then we should probably create issues to assign different things that need to be done to stop conflicts when making future commits.

**Comment by darrena092** [comment]
And just after a bit of research. I've found a way to deal with platform specific code. We could use the boost libraries (http://www.boost.org/). It has a lot of threading functions which means all we have to do is build against it, and code that works on Linux will work on Windows.

**Comment by Quaker762** [comment]
Sounds good, create a new repo on your account. I'm compiling against C++11 on Windows with MinGW, so no issue there. As for the way your handling cycles, sounds good the way it is, less work to do.

I'm using GIT for Windows, so I'll have to look into how to do a commit without creating a conflict.

As for boost, I'll have a look at it and familiarise myself with it.

**Comment by darrena092** [comment]
Alrighty, I'll get started on merging the code today and get the repository up. That's good, we shouldn't have any problems with compilers then.

I think it'd just be best if we work on specific sections of code at a time. Like I work on the GPU, you work on the CPU. That sort of thing.

I need to do the same. I've never used it before, but it looks like the solution to our cross platform problems haha.

Any ideas for a name for the merged project?

**Comment by darrena092** [comment]
Just one more thing. I noticed with my code that there are links between all sorts of classes for various things. I think in this merger it'd be good to start with a firm and agreed architectural design. I've attached it below. Let me know what you think.
gameboyemulator

**Comment by Quaker762** [comment]
Yeah sure I an work on implementing opcodes in the CPU.

As for a name, something like DMGe (DMG emulator) or something like that.

That architecture looks good, so basically the MMU is shared by most parts of the system, which sounds about right (everything is passed an MMU pointer or the likes?)

**Comment by darrena092** [comment]
Okay great :). DMGe sounds great. We should run with that.

Well the CPU and GPU will need shared usage of the MMU. But that block represents a system class also that handles the initialisation of the CPU and GPU, and also the cycles between them.

I'll get some merged code up ASAP.

**Comment by darrena092** [comment]
Created the repo. It just contains some boilerplate code at the minute.

If you could try building it on Windows, however, just to check if the threads start up correctly. It uses boost instead of pthreads on Linux.

**Comment by Quaker762** [comment]
Okay, after 3 hours, I've finally got boost compiled for Windows (Christ I hate compilers...) and it compiles with 0 errors and 0 warnings.

Also, should we call the debugger gbdb (like you did in wwgb), it has a really cool ring to it, even though we shouldn't worry about naming this early on.

**Comment by darrena092** [comment]
Haha nightmare. I think Windows is more to blame though, hence why I switched to Linux. Everything just makes more sense.

Yeah GameBoyDeBugger. I think that's a good idea.

Btw, if you want, just e-mail me with updates. I think we're abusing this pull request just a little lol. At gmail.com darrena092. Oh and did the threads start when you ran the boilerplate code I wrote?

**Comment by Quaker762** [comment]
Yeah sure I'll email you updates from now on, unless it's in a PR :P

Yeah the threads ran perfectly, no issue. Windows is a bitch, but someone's gotta do it lmao.

**Pull request merged**
